"""add_unique_constraint

Revision ID: 5a27b9227afa
Revises: cfe54747330d
Create Date: 2026-10-02 17:04:25.677805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a27b9227afa'
down_revision: Union[str, Sequence[str], None] = 'cfe54747330d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_appstime_date_app', 'appstime', ['date', 'app'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_appstime_date_app', 'appstime', type_='unique')
    # ### end Alembic commands ###
